services:
  redis:
    image: redis:latest
    container_name: redis_cache
    networks:
      - app_network

  app:
    container_name: throwin_backend
    build:
      context: .
    volumes:
      - .:/app:cached   # Keep code sync for development, optional for prod
       - staticfiles:/app/staticfiles   # REMOVE this line
    ports:
      - "8000:8000"
    command: sh /app/entrypoint.sh
    env_file:
      - ./throwin/.env
    depends_on:
      - redis
    networks:
      - app_network
    environment:
      - CELERY_BROKER_URL=redis://redis_cache:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_cache:6379/0

  celery_worker:
    container_name: throwin_celery_worker
    build:
      context: .
    volumes:
      - .:/app:cached
    command: celery -A throwin worker --loglevel=info
    env_file:
      - ./throwin/.env
    depends_on:
      - redis
    networks:
      - app_network

  celery_beat:
    container_name: throwin_celery_beat
    build:
      context: .
    volumes:
      - .:/app:cached
    command: celery -A throwin beat --loglevel=info
    env_file:
      - ./throwin/.env
    depends_on:
      - redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  staticfiles:
