# Generated by Django 5.1.2 on 2025-02-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='thank_message',
            field=models.CharField(blank=True, help_text="Thank you message for the user (e.g., 'Thank you for your support')", max_length=255, null=True),
        ),
    ]
