# Generated by Django 5.1.2 on 2025-02-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_thank_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agency_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
