# Generated by Django 5.1.2 on 2025-02-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_agency_code_userprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='corporate_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='agency_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
