# Generated by Django 5.1.2 on 2024-10-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_temporaryuser_options_temporaryuser_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fun_fact',
            field=models.CharField(blank=True, help_text="Short fun fact about the user (e.g., 'Eating and laughing')", max_length=255, null=True),
        ),
    ]
