# Generated by Django 5.1.2 on 2024-12-28 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_like_created_by_like_updated_by_and_more'),
        ('store', '0004_alter_store_banner_restaurant_store_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.restaurant'),
        ),
    ]
