# Generated by Django 5.1.2 on 2025-01-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='storeuser',
            name='unique_user_store_role',
        ),
    ]
