# Generated by Django 5.1.2 on 2025-01-21 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_storeuser_unique_user_store_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.UniqueConstraint(fields=('restaurant_owner',), name='unique_restaurant_owner'),
        ),
    ]
