# Generated by Django 5.1.2 on 2025-01-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_restaurant_unique_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='exposure',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('undefined', 'Undefined')], default='undefined', help_text='Exposure status for the store (public/private)', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='gacha_enabled',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('undefined', 'Undefined')], default='undefined', help_text='Gacha enabled status for the store (yes/no)', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='throwin_amounts',
            field=models.CharField(blank=True, help_text="Comma-separated list of throwin amounts (e.g., '1000,5000,10000'). Each value must be at least 500 and at most 49500.", max_length=255, null=True),
        ),
    ]
