# Generated by Django 5.1.2 on 2025-01-27 03:31

import django.contrib.postgres.fields
import django.core.validators
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_restaurant_unique_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='exposure',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('undefined', 'Undefined')], default='undefined', help_text='Exposure status for the store (public/private)', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='gacha_enabled',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('undefined', 'Undefined')], default='undefined', help_text='Gacha enabled status for the store (yes/no)', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='throwin_amounts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(49500)]), default=store.models.default_throwin_amounts, help_text='The amount of throwin for the store (min 500)', size=10),
        ),
    ]
