# Generated by Django 5.1.2 on 2025-02-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_restaurant_address_restaurant_corporate_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='corporate_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
