# Generated by Django 5.1.2 on 2025-02-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_restaurant_corporate_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='restaurantuser',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storeuser',
            options={'ordering': ['-created_at']},
        ),
    ]
