# Generated by Django 5.1.2 on 2025-01-07 08:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(blank=True, help_text='Nickname for the customer (anonymous or user-provided)', max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in the selected currency', max_digits=10)),
                ('currency', models.CharField(default='JPY', help_text='Currency of the payment', max_length=10)),
                ('transaction_id', models.CharField(blank=True, help_text='Unique identifier for the transaction from PayPal', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', help_text='Payment transaction status', max_length=20)),
                ('is_distributed', models.BooleanField(default=False, help_text='Indicates whether the payment has been distributed to the staff')),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of the payment initiation')),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('cash', 'Cash')], default='paypal', help_text='Payment method used by the customer', max_length=50)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Transaction fee deducted by the payment gateway', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Net amount received after deducting service fees', max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created Person')),
                ('customer', models.ForeignKey(blank=True, help_text='Authenticated customer making the payment (nullable for anonymous)', limit_choices_to={'kind': 'consumer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(help_text='The staff receiving the payment', limit_choices_to={'kind': 'restaurant_staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated Person')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'ordering': ['-payment_date'],
            },
        ),
    ]
