# Generated by Django 5.1.2 on 2025-01-08 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0001_initial'),
        ('store', '0002_remove_storeuser_unique_user_store_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='store',
            field=models.ForeignKey(blank=True, help_text='The store where the transaction occurred (nullable for unassigned staff)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_histories', to='store.store'),
        ),
    ]
