# Generated by Django 5.1.2 on 2025-01-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0002_alter_paymenthistory_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
