# Generated by Django 5.1.2 on 2024-12-02 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0003_alter_disbursementrequest_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disbursementrequest',
            options={},
        ),
    ]
