# Generated by Django 5.1.2 on 2025-02-13 04:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0003_paymenthistory_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted'), ('pending', 'Pending')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(help_text='Name of the bank (e.g., Mitsubishi UFJ, Mizuho, SMBC)', max_length=100)),
                ('bank_code', models.CharField(help_text='4-digit bank code', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Bank code must be exactly 4 digits.')])),
                ('branch_name', models.CharField(help_text='Branch name of the bank', max_length=100)),
                ('branch_code', models.CharField(help_text='3-digit branch code', max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Branch code must be exactly 3 digits.')])),
                ('account_number', models.CharField(help_text='Bank account number (7-16 digits)', max_length=16, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator('^\\d{7,16}$', 'Account number must be between 7-16 digits.')])),
                ('account_type', models.CharField(choices=[('futsuu', '普通 - Savings'), ('toza', '当座 - Current')], default='futsuu', help_text='Type of account: Savings (普通) or Current (当座)', max_length=10)),
                ('account_holder_name', models.CharField(help_text='Account holder name in Katakana', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Only one account can be active at a time.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created Person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated Person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'account_number')},
            },
        ),
    ]
