# Generated by Django 5.1.2 on 2024-12-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0004_alter_disbursementrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disbursementrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-created_at']},
        ),
    ]
