# Generated by Django 5.1.2 on 2025-02-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0004_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMOCreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('customer', models.CharField(max_length=255)),
                ('store', models.CharField(max_length=255)),
                ('restaurant', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('access_id', models.CharField(blank=True, max_length=100, null=True)),
                ('access_pass', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CAPTURE', 'Captured'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_code', models.CharField(blank=True, max_length=50, null=True)),
                ('process_date', models.DateTimeField(blank=True, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('expire_date', models.CharField(blank=True, max_length=5, null=True)),
                ('forward', models.CharField(blank=True, max_length=100, null=True)),
                ('pay_method', models.CharField(blank=True, max_length=50, null=True)),
                ('is_distributed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
