# Generated by Django 5.1.2 on 2024-12-02 07:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0005_alter_disbursementrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
