# Generated by Django 5.1.2 on 2025-02-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0005_gmocreditpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmocreditpayment',
            name='token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
