# Generated by Django 5.1.2 on 2025-02-24 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0006_gmocreditpayment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmocreditpayment',
            name='staff',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
