# Generated by Django 5.1.2 on 2025-01-05 09:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0007_disbursementrequest_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Payment History', 'verbose_name_plural': 'Payment Histories'},
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='customer_username',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='user_nick_name',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='currency',
            field=models.CharField(default='JPY', help_text='Currency of the payment', max_length=10),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='is_distributed',
            field=models.BooleanField(default=False, help_text='Indicates whether the payment has been distributed to the staff'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Net amount received after deducting service fees', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='nickname',
            field=models.CharField(blank=True, help_text='Optional nickname for anonymous payments', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time of the payment initiation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Transaction fee deducted by the payment gateway', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Payment amount in the selected currency', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Authenticated customer making the payment (nullable for anonymous)', limit_choices_to={'kind': 'CONSUMER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('cash', 'Cash')], default='paypal', help_text='Payment method used by the customer', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='staff',
            field=models.ForeignKey(help_text='The staff receiving the payment', limit_choices_to={'kind': 'RESTAURANT_STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', help_text='Payment transaction status', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the transaction from PayPal', max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='DisbursementRequest',
        ),
    ]
