# Generated by Django 5.1.2 on 2025-02-25 04:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0007_gmocreditpayment_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gmocreditpayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='gmocreditpayment',
            name='is_distributed',
        ),
        migrations.RemoveField(
            model_name='gmocreditpayment',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='gmocreditpayment',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='gmocreditpayment',
            name='store',
        ),
        migrations.AddField(
            model_name='gmocreditpayment',
            name='currency',
            field=models.CharField(default='JPY', help_text='Currency of the payment', max_length=10),
        ),
        migrations.AddField(
            model_name='gmocreditpayment',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Indicates if the payment has been processed'),
        ),
        migrations.AddField(
            model_name='gmocreditpayment',
            name='nickname',
            field=models.CharField(blank=True, help_text='Nickname for the payer (optional for unauthenticated users)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gmocreditpayment',
            name='restaurant_uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for restaurant'),
        ),
        migrations.AddField(
            model_name='gmocreditpayment',
            name='sales_agent_uid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, help_text='Unique identifier for sales agent (optional)', null=True),
        ),
        migrations.AddField(
            model_name='gmocreditpayment',
            name='staff_uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for staff receiving the tip'),
        ),
        migrations.AddField(
            model_name='gmocreditpayment',
            name='store_uid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, help_text='Unique identifier for store (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='gmocreditpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='gmocreditpayment',
            name='approval_code',
            field=models.CharField(blank=True, help_text='Approval code from GMO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gmocreditpayment',
            name='card_last4',
            field=models.CharField(blank=True, help_text='Last 4 digits of the credit card', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='gmocreditpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='gmocreditpayment',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Authenticated customer (nullable for anonymous users)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gmo_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gmocreditpayment',
            name='expire_date',
            field=models.CharField(blank=True, help_text='Credit card expiry date (MMYY)', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='gmocreditpayment',
            name='order_id',
            field=models.CharField(db_index=True, help_text='Unique identifier for the payment transaction', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gmocreditpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CAPTURE', 'Captured'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='PENDING', help_text='Status of the payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='gmocreditpayment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID generated by GMO', max_length=100, null=True),
        ),
    ]
