# Generated by Django 5.1.2 on 2025-01-05 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0008_alter_paymenthistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Authenticated customer making the payment (nullable for anonymous)', limit_choices_to={'kind': 'consumer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='staff',
            field=models.ForeignKey(help_text='The staff receiving the payment', limit_choices_to={'kind': 'restaurant_staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
