# Generated by Django 5.1.2 on 2025-02-26 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0008_alter_gmocreditpayment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmocreditpayment',
            name='restaurant_uid',
        ),
        migrations.RemoveField(
            model_name='gmocreditpayment',
            name='sales_agent_uid',
        ),
    ]
