# Generated by Django 5.1.2 on 2025-01-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0009_alter_paymenthistory_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='nickname',
            field=models.CharField(blank=True, help_text='Nickname for the customer (anonymous or user-provided)', max_length=50, null=True),
        ),
    ]
