# Generated by Django 5.1.2 on 2025-03-19 03:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0009_remove_gmocreditpayment_restaurant_uid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gmocreditpayment',
            name='is_distributed',
            field=models.BooleanField(default=False, help_text='Indicates if the payment amount has been distributed'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The current balance of the user', max_digits=12)),
                ('total_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The total amount received by the user', max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The last time the balance was updated')),
                ('user', models.OneToOneField(help_text='The user whose balance is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
