# Generated by Django 5.1.2 on 2025-03-19 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0010_gmocreditpayment_is_distributed_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('individual', 'Individual'), ('fc_admin', 'FC Admin'), ('glow_admin', 'Glow Admin')], default='individual', help_text='Indicates if the account is individual or shared (for FC Admin or Glow Admin).', max_length=20)),
                ('paypal_email', models.EmailField(help_text='The PayPal email address associated with the account.', max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Linked user for individual PayPal accounts. Use null for shared accounts.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The disbursed amount in JPY.', max_digits=12)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID returned by the PayPal API.', max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='The current status of the disbursement.', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message or error detail regarding the disbursement.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user receiving the disbursement.', on_delete=django.db.models.deletion.CASCADE, related_name='paypal_disbursements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
