# Generated by Django 5.1.2 on 2025-04-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0011_paypaldetail_paypaldisbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmocreditpayment',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
