# Generated by Django 5.1.2 on 2025-02-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gacha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gachahistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='spinbalance',
            options={'ordering': ['-created_at']},
        ),
    ]
