# Generated by Django 5.1.2 on 2025-04-08 04:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_service', '0011_paypaldetail_paypaldisbursement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted'), ('pending', 'Pending')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(blank=True, help_text='The type of payment this review is associated with.', max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='The transaction ID of the payment this review is associated with.', max_length=200, null=True)),
                ('consumer_name', models.CharField(default='Anonymous', help_text='The name of the consumer who wrote the review.', max_length=50)),
                ('message', models.TextField(help_text="The content of the customer's review message.")),
                ('consumer', models.ForeignKey(blank=True, help_text='The consumer who wrote the review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_consumer', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created Person')),
                ('payment', models.ForeignKey(blank=True, help_text='The payment transaction this review is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='payment_service.gmocreditpayment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated Person')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted'), ('pending', 'Pending')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(help_text='The content of the reply message.')),
                ('consumer', models.ForeignKey(blank=True, help_text='The user (consumer) who wrote the reply.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_consumed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created Person')),
                ('parent_reply', models.ForeignKey(blank=True, help_text='The direct parent reply, if this is a reply to another reply.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='review.reply')),
                ('restaurant_owner', models.ForeignKey(blank=True, help_text='The user (restaurant owner) who wrote the reply.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_restaurant_owner', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated Person')),
                ('review', models.ForeignKey(help_text='The initial review this reply belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='review.review')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
                'ordering': ['created_at'],
            },
        ),
    ]
