# Generated by Django 5.1.2 on 2025-04-08 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='store_uid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, help_text='Unique identifier for store (optional)', null=True),
        ),
    ]
