# Generated by Django 5.1.2 on 2025-04-09 03:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_store_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='staff_uid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, help_text='Unique identifier for staff receiving the tip', null=True),
        ),
    ]
