name: Django CI

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: your_db_name
          POSTGRES_USER: your_db_user
          POSTGRES_PASSWORD: your_db_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U your_db_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
        working-directory: ./Throwin-Backend # Set your correct subdirectory here

      - name: Run migrations
        env:
          DATABASE_URL: postgres://your_db_user:your_db_password@localhost/your_db_name
        run: |
          python manage.py migrate
        working-directory: ./Throwin-Backend # Set your correct subdirectory here

      - name: Run tests
        env:
          DATABASE_URL: postgres://your_db_user:your_db_password@localhost/your_db_name
        run: |
          python manage.py test
        working-directory: ./Throwin-Backend # Set your correct subdirectory here
