name: CI/CD for Throwin Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-1
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 084375572156.dkr.ecr.ap-northeast-1.amazonaws.com

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t throwin-backend .

      # Step 4: Tag the Docker image
      - name: Tag Docker Image
        run: |
          docker tag throwin-backend:latest 084375572156.dkr.ecr.ap-northeast-1.amazonaws.com/throwin-backend:latest

      # Step 5: Push the Docker image to ECR
      - name: Push Docker Image to ECR
        run: |
          docker push 084375572156.dkr.ecr.ap-northeast-1.amazonaws.com/throwin-backend:latest
